version: "3.3"
services:
  play-it-api:
    build: .
    environment:
      NODE_ENV: development
    ports:
      - "27465:3007"
    cpus: '0.01'
    mem_limit: '300M'
    logging:
      driver: "json-file"
      options:
        max-size: "50m"